apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  jwt-secret: azdIajltUXgycEx3OG5SdjNzVHo1eVVjMWJOdjZtS3E0ZlhyN3RZdzllWmEyc0RmOGdIajNnTHAwb0l1

  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=

  mongo-root-username: cm9vdA==
  mongo-root-password: cGFzc3dvcmQ=

  mongo-activity-username: YWN0aXZpdHl1c2Vy
  mongo-activity-password: YWN0aXZpdHlwYXNz