apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL..."
              until nc -z postgres-service 5432; do sleep 3; done;
              echo "PostgreSQL is ready!"
        - name: wait-for-mongo
          image: mongo:6.0
          command:
            - bash
            - -c
            - |
              echo "Waiting for MongoDB to be ready..."
              until mongosh --host mongo-service --port 27017 --eval "db.adminCommand('ping')" >/dev/null 2>&1; do
                sleep 2
              done
              echo "MongoDB is ready."
        - name: wait-for-localstack
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for LocalStack..."
              until nc -z localstack 4566; do sleep 3; done;
              echo "LocalStack is ready!"
        - name: wait-for-kafka
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Kafka..."
              until nc -z kafka-service 9092; do sleep 3; done;
              echo "Kafka is ready!"
        - name: wait-for-auth
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Authentication Service..."
              until nc -z authentication-service 8080; do sleep 3; done;
              echo "Authentication Service is ready!"
      containers:
        - name: image-service
          image: image-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/innowise"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: S3_ENDPOINT
              value: "http://localstack:4566"
            - name: S3_REGION
              value: "us-east-1"
            - name: S3_ACCESS_KEY
              value: "test"
            - name: S3_SECRET_KEY
              value: "test"
            - name: S3_BUCKET
              value: "images"
            - name: S3_EXTERNAL_URL
              value: "http://localhost:4566"
            - name: AUTH_SERVICE_URL
              value: "http://authentication-service:8080"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
            limits:
              memory: "2Gi"
              ephemeral-storage: "3Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30