server:
  port: ${SERVER_PORT:8082}

spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:activitydb}
      username: ${SPRING_DATA_MONGODB_USERNAME:activityuser}
      password: ${SPRING_DATA_MONGODB_PASSWORD:activitypass}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:activitydb}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
