apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: activity-service
          image: max3tmk/activity-service:1.0.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongo-service"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "activitydb"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: "activityuser"
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: "activitypass"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9093"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: activity-service
spec:
  selector:
    app: activity-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP