apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  01-init-users.js: |
    db = db.getSiblingDB('activitydb');
    db.createUser({
        user: 'activityuser',
        pwd: 'activitypass',
        roles: [{ role: 'readWrite', db: 'activitydb' }]
    });