server:
  port: ${SERVER_PORT:8085}
app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000}
spring:
  application:
    name: api-gateway
  liquibase:
    enabled: false
jwt:
  secret: ${JWT_SECRET:k7Hj9mQx2pLw8nRv3sTz5yUc1bNv6mKq4fXr7tYw9eZa2sDf8gHj3kLp0oIu}

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
  endpoint:
    health:
      show-details: always